name: build

on:
  # Trigger on push or pull request.
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install cc65
        run: sudo apt update && sudo apt install -y cc65

      - name: Build ROM image
        run: make

      - name: Check ROM image exists
        run: ROM1=rom1.bin && test -f $ROM1 && "File $ROM1 exists."

      - name: Check ROM image is correct size
        run: test "$(stat -c%s rom1.bin)" -eq 32768
